### ISSUE TITLE
demo run failed

### ISSUE THREAD

**Issue by FreeGIS** [wwwtyro/map-tile-lighting-demo#1]
`$ node tiled-demo.js
(node:7136) UnhandledPromiseRejectionWarning: ReferenceError: document is not de
fined
    at Object.getRegion (E:\github\map-tile-lighting-demo\demo.js:59:18)
    at main (E:\github\map-tile-lighting-demo\tiled-demo.js:19:28)
    at Object.<anonymous> (E:\github\map-tile-lighting-demo\tiled-demo.js:393:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
(node:7136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 3)
(node:7136) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.`

I find has code:
  `const canvas = document.createElement("canvas");
  canvas.width = image.width;
  canvas.height = image.height;
  document.body.appendChild(canvas);`
the documet is the content of html,i do not understand where can this demo work?  in  node or in html？

**Comment by atkinchris** [comment]
You need to run this from the `npm` script commands, defined in `package.json` - for example:

```
npm install
npm run tiled
```

You will need to create a new `mapbox.key` file containing your own Mapbox key.

**Comment by spatialhast** [comment]
when I run `'npm run tiled'` I have error in Chrome (Version 74.0.3729.157):
`TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.`
![image](https://user-images.githubusercontent.com/3269617/57762204-be23bb80-7707-11e9-9fac-61502df587a0.png)
